### PR TITLE
Fix for InternalsVisibleTo Conflict Warning

### PR DESCRIPTION
**Pull request by FXZFun**
## Summary
_First of all, I just want to note that I find this project to be very useful and reduces a lot of boilerplate code, so thanks for this awesome generator!_

This PR addresses an issue where projects using `InternalsVisibleTo` would encounter a CS0436 warning. The warning indicated a conflict between the generated AutoInterfaceAttribute from the projects with `InternalsVisibleTo` enabled. I have encountered this issue in a few other generators, and have fixed it using the approach outlined in [an article by Andrew Lock](https://andrewlock.net/creating-a-source-generator-part-7-solving-the-source-generator-marker-attribute-problem-part1/).

## Problem
Previously, when using AutoInterface in projects with InternalsVisibleTo enabled, the following warning would appear:

> [!WARNING] 
> ConsoleApp\Program.cs(24,2,24,15): warning CS0436: The type ‘AutoInterfaceAttribute’ in ‘ConsoleApp\obj\Debug\net8.0\generated\AutoInterface\AutoInterface.AutoInterfaceGenerator\AutoInterfaceAttribute.g.cs’ conflicts with the imported type ‘AutoInterfaceAttribute’ in ‘AnotherApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null’. Using the type defined in ‘ConsoleApp\obj\Debug\net8.0\generated\AutoInterface\AutoInterface.AutoInterfaceGenerator\AutoInterfaceAttribute.g.cs’.

The issue arose because the InternalsVisibleTo attribute allowed the project to see internal types from both the current project and the referenced project. While I believe the `AUTOINTERFACE_EXCLUDE_ATTRIBUTES` constant is supposed to address this (I have tried this method too), it doesn't seem to work to resolve the issue. 

## Solution
The issue was resolved by modifying how the attributes were included in the generated code. This change follows the approach outlined in [Andrew Lock’s article](https://andrewlock.net/creating-a-source-generator-part-7-solving-the-source-generator-marker-attribute-problem-part1/). The new implementation ensures that the generated AutoInterfaceAttribute does not conflict with other projects. This is accomplished by moving the attributes to a separate project, and packing that assembly in the package as both a generator reference and as a library, as detailed in the [second part of the article](https://andrewlock.net/creating-a-source-generator-part-7-solving-the-source-generator-marker-attribute-problem-part2/).

## Testing
I updated the unit tests to reference the attribute assembly and verified that the CS0436 warning no longer appears in our projects using InternalsVisibleTo.

## References
https://andrewlock.net/creating-a-source-generator-part-7-solving-the-source-generator-marker-attribute-problem-part1/
https://andrewlock.net/creating-a-source-generator-part-7-solving-the-source-generator-marker-attribute-problem-part2/
https://github.com/andrewlock/StronglyTypedId/issues/38

### CODE REVIEW

**Comment by BlackWhiteYoshi** [comment]
Why does *AUTOINTERFACE_EXCLUDE_ATTRIBUTES* not work?

**Comment by FXZFun** [comment]
In most cases, the `AUTOINTERFACE_EXCLUDE_ATTRIBUTES` constant effectively resolves conflicts. However, there was an obscure scenario within our organization’s codebase where it didn’t fully address the issue between projects. Although I don’t recall the specific details, a similar problem with another internal source generator was successfully resolved by applying this pattern.

Overall, following this approach of incorporating the attributes appears to be a much cleaner solution than defining the constant in each project with shared internals.

**Comment by BlackWhiteYoshi** [comment]
So, you cannot or refuse to describe your problem and expect that I merge a fix for something, that is probably not even broken.


Regardless of the scenario, I'll won't merge your PR and I leave you with 3 reasons why:

1. PR Changes

After a quick look at your changes, I've seen several issues:

 - AUTOINTERFACE_EXCLUDE_ATTRIBUTES is useless
 
You moved the attributes in a class Library, but left the *#if !AUTOINTERFACE_EXCLUDE_ATTRIBUTES* directive in there. The preprocessor directive makes no sense at that place. Enabling it in *AutoInterface.Attributes* will just compile an empty class library and the NuGet package will be without attributes.  
Strictly this is also a breaking change, since you cannot use this functionality anymore.

 - nullable *AutoInterfaceAttribute* properties

You changed the type of the properties inside the class *AutoInterfaceAttribute* from non-nullable reference types to nullable reference types. That means when using this attribute, setting a property to the value *null* is valid and meaningful. First, setting any of these values to *null* has no meaning and second, I don't even know if setting to *null* is even valid, at least I never tested it. I would not be surprised if the generator dies in an exception.  
That is a change that should be also mentioned in the commit message.

 - suppress package warning

You added *&lt;NoPackageAnalysis&gt;true&lt;/NoPackageAnalysis&gt;* with the commit message "fix warning when packing generator". Suppressing a warning is not fixing it, especially when the warning is legit. Setting the dependencies in the *.nuspec* file is not meaningless. And doing so is quite easy, just removing *&lt;SuppressDependenciesWhenPacking&gt;true&lt;/SuppressDependenciesWhenPacking&gt;* and the SDK will at the dependencies.  
Another warning you suppress is *IDE0130*. I also do not like this warning, but again, without mention it in the commit message.

 - packaging the AutoInterface.Attributes.dll twice

You packaged the dll twice, once in the analyzers folder and once in the lib folder. Packaging the attributes in the analyzer folder is completely unnecessary, since the analyzer does not use any of these classes.

 - [Conditional("AUTO_INTERFACE_USAGES")]

You added the *[Conditional("AUTO_INTERFACE_USAGES")]*-attribute to the attributes without mention it anywhere. Especially the arbitrary chosen string *"AUTO_INTERFACE_USAGES"* must be mentioned in the README.md. And again, strictly this is also a breaking change, because someone could use reflection to do logic based on these attributes.

 - line endings

This is only a minor thing, but the entire code base uses spaces to indent and LF line endings. You introduced CRLF line endings. This can be annoying when comparing diffs.


2. Edge Case

You should keep in mind that this is an edge case. The InternalsVisibleToAttribute should normally not be used. The only good reason I can think of to use this attribute is for testing. And test projects normally do not need AutoInterface. And if they do for some reason, you can still use the *AUTOINTERFACE_EXCLUDE_ATTRIBUTES* constant.

You say it is much cleaner to put the attributes in a class library, but I don't think so. It's a tradeoff. By splitting it up in a generator and a class library you increase the complexity a lot. You introduce another dependency, a runtime dependency. So, the package will include a dev-dependency and a runtime-dependency, instead just a dev-dependency. And I personally find it much cleaner when a package only contains dev dependencies, it's much easier to reason about. Also on the development side you have to deal with both projects, and you have already done 2 mistakes in the package process.

On the other hand you get the benefit you are looking for: You can't get duplicates.  
But it is this really worth it? The only scenario I can think of this could be beneficial is when you have a messed-up codebase with hundreds of projects and InternalsVisibleToAttributes all over the place. And I personally do not care about supporting messed up codebases. So, in my opinion it is not worth it.


3. Attitude

By looking at your PR I get the impression that you are not an expert in this field. But still, you are trying to present yourself as one. You come out of the blue with a PR, writing how important and great it is, underlying it with a referral to a well-known member in the community, while writing generic commit messages to hide your uncertainties. This "Trust me Bro" attitude is something I really don't like. That is simply not trustworthy and itself reason enough to decline your request.

A better way to do it is to discuss things first, coming up to a conclusion together and then start working on it.  


I hope my criticism is not too destructive and somewhat understandable. I know you are just trying to fix a problem, but in my opinion the problem should be solved in your codebase and not in my library. Believe me or not, but normal code bases don't have this problem.

**Comment by FXZFun** [comment]
Thanks for taking the time to provide such detailed feedback. I appreciate the review and acknowledge the valid points you've raised. While there some things I don't fully agree with, I see room for improvement based on your suggestions.

I understand this is an edge case and therefore not top priority. I encountered an issue and attempted to implement a solution based on the approach linked in the article. As you said, it is a trade off, and may not be a direction you want to go with this project. Since some other requirements changed, we were able to get the existing method to work, so I am willing to drop the issue since I don't have a repro project to share.

Your impression would be correct, I never claimed to be an expert on source generators. My intention was to address an issue I encountered and share my solution. The article I linked was meant to provide context, not credibility. I apologize if it came across as presumptuous and not trustworthy.
It's good to know that you are receptive to discussions around PR changes, as I hadn't gotten that impression from previous issues. Many authors won't take the time to engage in discussions, they just want the changes.

That being said, I do appreciate the response and will close this PR accordingly.

**Pull request closed without merging**
